export const AHALERA_BATUA = {
  nor: {
    ni: "naiteke",
    hura: "daiteke",
    gu: "gaitezke",
    zu: "zaitezke",
    zuek: "zaitezkete",
    haiek: "daitezke",
  },
  norNori: {
    ni: {
      hari: "nakioke",
      zuri: "nakizuke",
      zuei: "nakizueke",
      haiei: "nakieke",
    },
    hura: {
      niri: "dakidake",
      hari: "dakioke",
      guri: "dakiguke",
      zuri: "dakizuke",
      zuei: "dakizueke",
      haiei: "dakieke",
    },
    gu: {
      hari: "gakizkioke",
      zuri: "gakizkizuke",
      zuei: "gakizkizueke",
      haiei: "gakizkieke",
    },
    zu: {
      niri: "zakizkidake",
      hari: "zakizkioke",
      guri: "zakizkiguke",
      haiei: "zakizkieke",
    },
    zuek: {
      niri: "zakizkidakete",
      hari: "zakizkiokete",
      guri: "zakizkigukete",
      haiei: "zakizkiekete",
    },
    haiek: {
      niri: "dakizkidake",
      hari: "dakizkioke",
      guri: "dakizkiguke",
      zuri: "dakizkizuke",
      zuei: "dakizkizueke",
      haiei: "dakizkieke",
    },
  },
  norNork: {
    nik: {
      hura: "dezaket",
      zu: "zaitzaket",
      zuek: "zaitzaketet",
      haiek: "ditzaket",
    },
    hark: {
      ni: "nazake",
      hura: "dezake",
      gu: "gaitzake",
      zu: "zaitzake",
      zuek: "zaitzakete",
      haiek: "ditzake",
    },
    guk: {
      hura: "dezakegu",
      zu: "zaitzakegu",
      zuek: "zaitzaketegu",
      haiek: "ditzakegu",
    },
    zuk: {
      ni: "nazakezu",
      hura: "dezakezu",
      gu: "gaitzakezu",
      haiek: "ditzakezu",
    },
    zuek: {
      ni: "nazakezue",
      hura: "dezakezue",
      gu: "gaitzakezue",
      haiek: "ditzakezue",
    },
    haiek: {
      ni: "nazakete",
      hura: "dezakete",
      gu: "gaitzakete",
      zu: "zaitzakete",
      zuek: "zaitzaketete",
      haiek: "ditzakete",
    },
  },
  norNoriNorkS: {
    nik: {
      hari: "diezaioket",
      zuri: "diezazuket",
      zuei: "diezazueket",
      haiei: "diezaieket",
    },
    hark: {
      niri: "diezadake",
      hari: "diezaioke",
      guri: "diezaguke",
      zuri: "diezazuke",
      zuei: "diezazueke",
      haiei: "diezaieke",
    },
    guk: {
      hari: "diezaiokegu",
      zuri: "diezazukegu",
      zuei: "diezazuekegu",
      haiei: "diezaiekegu",
    },
    zuk: {
      niri: "diezadakezu",
      hari: "diezaiokezu",
      guri: "diezagukezu",
      haiei: "diezaiekezu",
    },
    zuek: {
      niri: "diezadakezue",
      hari: "diezaiokezue",
      guri: "diezagukezue",
      haiei: "diezaiekezue",
    },
    haiek: {
      niri: "diezadakete",
      hari: "diezaiokete",
      guri: "diezagukete",
      zuri: "diezazukete",
      zuei: "diezazuekete",
      haiei: "diezaiekete",
    },
  },
  norNoriNorkP: {
    nik: {
      hari: "diezazkioket",
      zuri: "diezazkizuket",
      zuei: "diezakizueket",
      haiei: "diezazkieket",
    },
    hark: {
      niri: "diezazkidake",
      hari: "diezazkioke",
      guri: "diezazkiguke",
      zuri: "diezazkizuke",
      zuei: "diezazkizueke",
      haiei: "diezazkieke",
    },
    guk: {
      hari: "diezazkiokegu",
      zuri: "diezazkizukegu",
      zuei: "diezazkizuekegu",
      haiei: "diezazkiekegu",
    },
    zuk: {
      niri: "diezazkidakezu",
      hari: "diezazkiokezu",
      guri: "diezazkigukezu",
      haiei: "diezazkiekezu",
    },
    zuek: {
      niri: "diezazkidakezue",
      hari: "diezazkiokezue",
      guri: "diezazkigukezue",
      haiei: "diezazkiekezue",
    },
    haiek: {
      niri: "diezazkidakete",
      hari: "diezazkiokete",
      guri: "diezazkigukete",
      zuri: "diezazkizukete",
      zuei: "diezazkizuekete",
      haiei: "diezazkiekete",
    },
  },
};

export const AHALERA_BATUA_ZUTANOA_LEHEN = {
  nor: {
    ni: "",
    hura: "",
    gu: "",
    zu: "",
    zuek: "",
    haiek: "",
  },
  norNori: {
    ni: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hura: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    gu: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zu: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
  norNork: {
    nik: {
      hura: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    hark: {
      ni: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    guk: {
      hura: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    zuk: {
      ni: "",
      hura: "",
      gu: "",
      haiek: "",
    },
    zuek: {
      ni: "",
      hura: "",
      gu: "",
      haiek: "",
    },
    haiek: {
      ni: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
  },
  norNoriNorkS: {
    nik: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hark: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    guk: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zuk: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
  norNoriNorkP: {
    nik: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hark: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    guk: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zuk: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
};

export const AHALERA_BATUA_ZUTANOA_ALEGIAZKOA = {
  nor: {
    ni: "",
    hura: "",
    gu: "",
    zu: "",
    zuek: "",
    haiek: "",
  },
  norNori: {
    ni: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hura: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    gu: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zu: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
  norNork: {
    nik: {
      hura: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    hark: {
      ni: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    guk: {
      hura: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    zuk: {
      ni: "",
      hura: "",
      gu: "",
      haiek: "",
    },
    zuek: {
      ni: "",
      hura: "",
      gu: "",
      haiek: "",
    },
    haiek: {
      ni: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
  },
  norNoriNorkS: {
    nik: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hark: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    guk: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zuk: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
  norNoriNorkP: {
    nik: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    hark: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    guk: {
      hari: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
    zuk: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    zuek: {
      niri: "",
      hari: "",
      guri: "",
      haiei: "",
    },
    haiek: {
      niri: "",
      hari: "",
      guri: "",
      zuri: "",
      zuei: "",
      haiei: "",
    },
  },
};
