import { IIndikatiboaBatua } from "../../common/types/indikatiboaBatua.types";

export const INDIKATIBOA_BATUA: IIndikatiboaBatua = {
  orain: {
    nor: {
      ni: "naiz | nauk / naun",
      hi: "haiz",
      hura: "da | duk / dun",
      gu: "gara | gaituk / gaitun",
      zu: "zara",
      zuek: "zarete",
      haiek: "dira | dituk / ditun",
    },
    nor_nori: {
      ni: {
        hiri: "natzaik / natzain",
        hari: "natzaio | natzaiok / natzaion",
        zuri: "natzaizu",
        zuei: "natzaizue",
        haiei: "natzaie | natzaiek / natzaien",
      },
      hi: {
        niri: "hatzait",
        hari: "hatzaio",
        guri: "hatzaigu",
        haiei: "hatzaie",
      },
      hura: {
        niri: "zait | zaidak / zaidan",
        hiri: "zaik | zain",
        hari: "zaio | zaiok / zaion",
        guri: "zaigu | zaiguk / zaigun",
        zuri: "zaizu",
        zuei: "zaizue",
        haiei: "zaie | zaiek / zaien",
      },
      gu: {
        hiri: "gatzaizkik / gatzaizkin",
        hari: "gatzaizkio | gatzaizkiok / gatzaizkion",
        zuri: "gatzaizkizu",
        zuei: "gatzaizkizue",
        haiei: "gatzaizkie | gatzaizkiek / gatzaizkien",
      },
      zu: {
        niri: "zatzaizkit",
        hari: "zatzaizkio",
        guri: "zatzaizkigu",
        haiei: "zatzaizkie",
      },
      zuek: {
        niri: "zatzaizkidate",
        hari: "zatzaizkiote",
        guri: "zatzaizkigute",
        haiei: "zatzaizkiete",
      },
      haiek: {
        niri: "zaizkit | zaizkidak / zaizkidan",
        hiri: "zaizkik / zaizkin",
        hari: "zaizkio | zaizkiok / zaizkion",
        guri: "zaizkigu | zaizkiguk / zaizkigun",
        zuri: "zaizkizu",
        zuei: "zaizkizue",
        haiei: "zaizkie | zaizkiek / zaizkien",
      },
    },
    nor_nork: {
      nik: {
        hi: "haut",
        hura: "dut | diat / dinat",
        zu: "zaitut",
        zuek: "zaituztet",
        haiek: "ditut | ditiat / ditinat",
      },
      hik: {
        ni: "nauk / naun",
        hura: "duk / dun",
        gu: "gaituk / gaitun",
        haiek: "dituk / ditun",
      },
      hark: {
        ni: "nau | naik / nain",
        hi: "hau",
        hura: "du | dik / din",
        gu: "gaitu | gaitik / gaitin",
        zu: "zaitu",
        zuek: "zaituzte",
        haiek: "ditu | ditik / ditin",
      },
      guk: {
        hi: "haugu",
        hura: "dugu | diagu / dinagu",
        zu: "zaitugu",
        zuek: "zaituztegu",
        haiek: "ditugu | ditiagu / ditinagu",
      },
      zuk: {
        ni: "nauzu",
        hura: "duzu",
        gu: "gaituzu",
        haiek: "dituzu",
      },
      zuek: {
        ni: "nauzue",
        hura: "duzue",
        gu: "gaituzue",
        haiek: "dituzue",
      },
      haiek: {
        ni: "naute | naitek / naiten",
        hi: "haute",
        hura: "dute | ditek / diten",
        gu: "gaituzte | gaitiztek / gaitizten",
        zu: "zaituzte",
        zuek: "zaituztete",
        haiek: "dituzte | ditiztek / ditizten",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "diat / dinat",
          hari: "diot | zioat / zionat",
          zuri: "dizut",
          zuei: "dizuet",
          haiei: "diet | zieat / zienat",
        },
        hik: {
          niri: "didak / didan",
          hari: "diok / dion",
          guri: "diguk / digun",
          haiei: "diek / dien",
        },
        hark: {
          niri: "dit | zidak / zidan",
          hiri: "dik / din",
          hari: "dio | ziok / zion",
          guri: "digu | ziguk / zigun",
          zuri: "dizu",
          zuei: "dizue",
          haiei: "die | ziek / zien",
        },
        guk: {
          hiri: "diagu / dinagu",
          hari: "diogu | zioagu / zionagu",
          zuri: "dizugu",
          zuei: "dizuegu",
          haiei: "diegu | zieagu / zienagu",
        },
        zuk: {
          niri: "didazu",
          hari: "diozu",
          guri: "diguzu",
          haiei: "diezu",
        },
        zuek: {
          niri: "didazue",
          hari: "diozue",
          guri: "diguzue",
          haiei: "diezue",
        },
        haiek: {
          niri: "didate | zidatek / zidaten",
          hiri: "diate / dinate",
          hari: "diote | ziotek / zioten",
          guri: "digute | zigutek / ziguten",
          zuri: "dizute",
          zuei: "dizuete",
          haiei: "diete | zietek / zieten",
        },
      },
      plurala: {
        nik: {
          hiri: "dizkiat / dizkinat",
          hari: "dizkiot | zizkioat / zizkionat",
          zuri: "dizkizut",
          zuei: "dizkizuet",
          haiei: "dizkiet | zizkieat / zizkienat",
        },
        hik: {
          niri: "dizkidak / dizkidan",
          hari: "dizkiok / dizkion",
          guri: "dizkiguk / dizkigun",
          haiei: "dizkiek / dizkien",
        },
        hark: {
          niri: "dizkit | zizkidak / zizkidan",
          hiri: "dizkik / dizkin",
          hari: "dizkio | zizkiok / zizkion",
          guri: "dizkigu | zizkiguk / zizkigun",
          zuri: "dizkizu",
          zuei: "dizkizue",
          haiei: "dizkie | zizkiek / zizkien",
        },
        guk: {
          hiri: "dizkiagu / dizkinagu",
          hari: "dizkiogu | zizkioagu / zizkionagu",
          zuri: "dizkizugu",
          zuei: "dizkizuegu",
          haiei: "dizkiegu | zizkieagu / zizkienagu",
        },
        zuk: {
          niri: "dizkidazu",
          hari: "dizkiozu",
          guri: "dizkiguzu",
          haiei: "dizkiezu",
        },
        zuek: {
          niri: "dizkidazue",
          hari: "dizkiozue",
          guri: "dizkiguzue",
          haiei: "dizkiezue",
        },
        haiek: {
          niri: "dizkidate | zizkidatek / zizkidaten",
          hiri: "dizkiate / dizkinate",
          hari: "dizkiote | zizkiotek / zizkioten",
          guri: "dizkigute | zizkigutek / zizkiguten",
          zuri: "dizkizute",
          zuei: "dizkizuete",
          haiei: "dizkiete | zizkietek / zizkieten",
        },
      },
    },
  },
  lehen: {
    nor: {
      ni: "nintzen | ninduan / nindunan",
      hi: "hintzen",
      hura: "zen | zuan / zunan",
      gu: "ginen | gintuan / gintunan",
      zu: "zinen",
      zuek: "zineten",
      haiek: "ziren | zituan / zitunan",
    },
    nor_nori: {
      ni: {
        hiri: "nintzaian / nintzainan",
        hari: "nintzaion | nintzaioan / nintzaionan",
        zuri: "nintzaizun",
        zuei: "nintzaizuen",
        haiei: "nintzaien | nintzaiean / nintzaienan",
      },
      hi: {
        niri: "hintzaidan",
        hari: "hintzaion",
        guri: "hintzaigun",
        haiei: "hintzaien",
      },
      hura: {
        niri: "zitzaidan | zitzaidaan / zitzaidanan",
        hiri: "zitzaian / zitzainan",
        hari: "zitzaion | zitzaioan / zitzaionan",
        guri: "zitzaigun | zitzaiguan / zitzaigunan",
        zuri: "zitzaizun",
        zuei: "zitzaizuen",
        haiei: "zitzaien | zitzaiean / zitzaienan",
      },
      gu: {
        hiri: "gintzaizkian / gintzaizkinan",
        hari: "gintzaizkion | gintzaizkioan / gintzaizkionan",
        zuri: "gintzaizkizun",
        zuei: "gintzaizkizuen",
        haiei: "gintzaizkien | gintzaizkiean / gintzaizkienan",
      },
      zu: {
        niri: "zintzaizkidan",
        hari: "zintzaizkion",
        guri: "zintzaizkigun",
        haiei: "zintzaizkien",
      },
      zuek: {
        niri: "zintzaizkidaten",
        hari: "zintzaizkioten",
        guri: "zintzaizkiguten",
        haiei: "zintzaizkieten",
      },
      haiek: {
        niri: "zitzaizkidan | zitzaizkidaan / zitzaizkidanan",
        hiri: "zitzaizkian / zitzaizkinan",
        hari: "zitzaizkion | zitzaizkioan / zitzaizkionan",
        guri: "zitzaizkigun | zitzaizkiguan / zitzaizkigunan",
        zuri: "zitzaizkizun",
        zuei: "zitzaizkizuen",
        haiei: "zitzaizkien | zitzaizkiean / zitzaizkienan",
      },
    },
    nor_nork: {
      nik: {
        hi: "hindudan",
        hura: "nuen | nian / ninan",
        zu: "zintudan",
        zuek: "zintuztedan",
        haiek: "nituen | nitian / nitinan",
      },
      hik: {
        ni: "ninduan / nindunan",
        hura: "huen",
        gu: "gintuan / gintunan",
        haiek: "hituen",
      },
      hark: {
        ni: "ninduen | nindian / nindinan",
        hi: "hinduen",
        hura: "zuen | zian / zinan",
        gu: "gintuen | gintian / gintinan",
        zu: "zintuen",
        zuek: "zintuzten",
        haiek: "zituen | zitian / zitinan",
      },
      guk: {
        hi: "hindugun",
        hura: "genuen | genian / geninan",
        zu: "zintugun",
        zuek: "zintuztegun",
        haiek: "genituen | genitian / genitinan",
      },
      zuk: {
        ni: "ninduzun",
        hura: "zenuen",
        gu: "gintuzun",
        haiek: "zenituen",
      },
      zuek: {
        ni: "ninduzuen",
        hura: "zenuten",
        gu: "gintuzuen",
        haiek: "zenituzten",
      },
      haiek: {
        ni: "ninduten | ninditean / ninditenan",
        hi: "hinduten",
        hura: "zuten | zitean / zitenan",
        gu: "gintuzten | gintiztean / gintiztenan",
        zu: "zintuzten",
        zuek: "zintuzteten",
        haiek: "zituzten | zitiztean / zitiztenan",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "nian / ninan",
          hari: "nion | nioan / nionan",
          zuri: "nizun",
          zuei: "nizuen",
          haiei: "nien | niean / nienan",
        },
        hik: {
          niri: "hidan",
          hari: "hion",
          guri: "higun",
          haiei: "hien",
        },
        hark: {
          niri: "zidan | zidaan / zidanan",
          hiri: "zian / zinan",
          hari: "zion | zioan / zionan",
          guri: "zigun | ziguan / zigunan",
          zuri: "zizun",
          zuei: "zizuen",
          haiei: "zien | ziean / zienan",
        },
        guk: {
          hiri: "genian / geninan",
          hari: "genion | genioan / genionan",
          zuri: "genizun",
          zuei: "genizuen",
          haiei: "genien | geniean / genienan",
        },
        zuk: {
          niri: "zenidan",
          hari: "zenion",
          guri: "zenigun",
          haiei: "zenien",
        },
        zuek: {
          niri: "zenidaten",
          hari: "zenioten",
          guri: "zeniguten",
          haiei: "zenieten",
        },
        haiek: {
          niri: "zidaten | zidatean / zidatenan",
          hiri: "ziaten / zinaten",
          hari: "zioten | ziotean / ziotenan",
          guri: "ziguten | zigutean / zigutenan",
          zuri: "zizuten",
          zuei: "zizueten",
          haiei: "zieten | zietean / zietenan",
        },
      },
      plurala: {
        nik: {
          hiri: "nizkian / nizkinan",
          hari: "nizkion | nizkioan / nizkionan",
          zuri: "nizkizun",
          zuei: "nizkizuen",
          haiei: "nizkien | nizkiean / nizkienan",
        },
        hik: {
          niri: "hizkidan",
          hari: "hizkion",
          guri: "hizkigun",
          haiei: "hizkien",
        },
        hark: {
          niri: "zizkidan | zizkidaan / zizkidanan",
          hiri: "zizkian / zizkinan",
          hari: "zizkion | zizkioan / zizkionan",
          guri: "zizkigun | zizkiguan / zizkigunan",
          zuri: "zizkuzun",
          zuei: "zizkizuen",
          haiei: "zizkien | zizkiean / zizkienan",
        },
        guk: {
          hiri: "genizkian / genizkinan",
          hari: "genizkion | genizkioan / genizkionan",
          zuri: "genizkizun",
          zuei: "genizkizuen",
          haiei: "genizkien | genizkiean / genizkienan",
        },
        zuk: {
          niri: "zenizkidan",
          hari: "zenizkion",
          guri: "zenizkigun",
          haiei: "zenizkien",
        },
        zuek: {
          niri: "zenizkidaten",
          hari: "zenizkioten",
          guri: "zenizkiguten",
          haiei: "zenizkieten",
        },
        haiek: {
          niri: "zizkidaten | zizkidatean / zizkidatenan",
          hiri: "zizkiaten / zizkinaten",
          hari: "zizkioten | zizkiotean / zizkiotenan",
          guri: "zizkiguten | zizkigutean / zizkigutenan",
          zuri: "zizkizuten",
          zuei: "zizkizueten",
          haiei: "zizkieten | zizkietean / zizkietenan",
        },
      },
    },
  },
  baldintza: {
    nor: {
      ni: "banintz",
      hi: "bahintz",
      hura: "balitz",
      gu: "bagina",
      zu: "bazina",
      zuek: "bazinete",
      haiek: "balira",
    },
    nor_nori: {
      ni: {
        hiri: "banintzaik / banintzain",
        hari: "banintzaio",
        zuri: "banintzaizu",
        zuei: "banintzaizue",
        haiei: "banintzaie",
      },
      hi: {
        niri: "bahintzait",
        hari: "bahintzaio",
        guri: "bahintzaigu",
        haiei: "bahintzaie",
      },
      hura: {
        niri: "balitzai",
        hiri: "balitzaik / balitzain",
        hari: "balitzaio",
        guri: "balitzaigu",
        zuri: "balitzaizu",
        zuei: "balitzaizue",
        haiei: "balitzaie",
      },
      gu: {
        hiri: "bagintzaizkik / bagintzaizkin",
        hari: "bagintzaizkio",
        zuri: "bagintzaizkizu",
        zuei: "bagintzaizkizue",
        haiei: "bagintzaizkie",
      },
      zu: {
        niri: "bazintzaizkit",
        hari: "bazintzaizkio",
        guri: "bazintzaizkigu",
        haiei: "bazintzaizkie",
      },
      zuek: {
        niri: "bazintzaizkidate",
        hari: "bazintzaizkiote",
        guri: "bazintzaizkigute",
        haiei: "bazintzaizkiete",
      },
      haiek: {
        niri: "balitzaizkit",
        hiri: "balitzaizkik / balitzaizkin",
        hari: "balitzaizkio",
        guri: "balitzaizkigu",
        zuri: "balitzaizkizu",
        zuei: "balitzaizkizue",
        haiei: "balitzaizkie",
      },
    },
    nor_nork: {
      nik: {
        hi: "bahindut",
        hura: "banu",
        zu: "bazintut",
        zuek: "bazintuztet",
        haiek: "banitu",
      },
      hik: {
        ni: "baninduk / banindun",
        hura: "bahu",
        gu: "bagintuk / bagintun",
        haiek: "bahitu",
      },
      hark: {
        ni: "banindu",
        hi: "bahindu",
        hura: "balu",
        gu: "bagintu",
        zu: "bazintu",
        zuek: "bazintuzte",
        haiek: "balitu",
      },
      guk: {
        hi: "bahindugu",
        hura: "bagenu",
        zu: "bazintugu",
        zuek: "bazintuztegu",
        haiek: "bagenitu",
      },
      zuk: {
        ni: "baninduzu",
        hura: "bazenu",
        gu: "bagintuzu",
        haiek: "bazenitu",
      },
      zuek: {
        ni: "baninduzue",
        hura: "bazenute",
        gu: "bagintuzue",
        haiek: "bazenituzte",
      },
      haiek: {
        ni: "banindute",
        hi: "bahindute",
        hura: "balute",
        gu: "bagintuzte",
        zu: "bazintuzte",
        zuek: "bazintuztete",
        haiek: "balituzte",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "banik / banin",
          hari: "banio",
          zuri: "banizu",
          zuei: "banizue",
          haiei: "banie",
        },
        hik: {
          niri: "bahit",
          hari: "bahio",
          guri: "bahigu",
          haiei: "bahie",
        },
        hark: {
          niri: "balit",
          hiri: "balik / balin",
          hari: "balio",
          guri: "baligu",
          zuri: "balizu",
          zuei: "balizue",
          haiei: "balie",
        },
        guk: {
          hiri: "bagenik / bagenin",
          hari: "bagenio",
          zuri: "bagenizu",
          zuei: "bagenizue",
          haiei: "bagenie",
        },
        zuk: {
          niri: "bazenit",
          hari: "bazenio",
          guri: "bazenigu",
          haiei: "bazenie",
        },
        zuek: {
          niri: "bazenidate",
          hari: "bazeniote",
          guri: "bazenigute",
          haiei: "bazeniete",
        },
        haiek: {
          niri: "balidate",
          hiri: "baliate / balinate",
          hari: "baliote",
          guri: "baligute",
          zuri: "balizute",
          zuei: "balizuete",
          haiei: "baliete",
        },
      },
      plurala: {
        nik: {
          hiri: "banizkik / banizkin",
          hari: "banizkio",
          zuri: "banizkizu",
          zuei: "banizkizue",
          haiei: "banizkie",
        },
        hik: {
          niri: "bahizkit",
          hari: "bahizkio",
          guri: "bahizkigu",
          haiei: "bahizkie",
        },
        hark: {
          niri: "balizkit",
          hiri: "balizkik / balizkin",
          hari: "balizkio",
          guri: "balizkigu",
          zuri: "balizkizu",
          zuei: "balizkizue",
          haiei: "balizkie",
        },
        guk: {
          hiri: "bagenizkik / bagenizkin",
          hari: "bagenizkio",
          zuri: "bagenizkizu",
          zuei: "bagenizkizue",
          haiei: "bagenizkie",
        },
        zuk: {
          niri: "bazenizkit",
          hari: "bazenizkio",
          guri: "bazenizkigu",
          haiei: "bazenizkie",
        },
        zuek: {
          niri: "bazenizkidate",
          hari: "bazenizkiote",
          guri: "bazenizkigute",
          haiei: "bazenizkiete",
        },
        haiek: {
          niri: "balizkidate",
          hiri: "balizkiate / balizkinate",
          hari: "balizkiote",
          guri: "balizkigute",
          zuri: "balizkizute",
          zuei: "balizkizuete",
          haiei: "balizkiete",
        },
      },
    },
  },
  etorkizunekoa: {
    nor: {
      ni: "nintzateke | nindukek / ninduken",
      hi: "hintzateke",
      hura: "litzateke | lukek / luken",
      gu: "ginateke | gintuzkek / gintuzken",
      zu: "zinateke",
      zuek: "zinatekete",
      haiek: "lirateke | lituzkek / lituzken",
    },
    nor_nori: {
      ni: {
        hiri: "nintzaiake / nintzainake",
        hari: "nintzaioke | nintzaiokek / nintzaioken",
        zuri: "nintzaizuke",
        zuei: "nintzaizueke",
        haiei: "nintzaieke | nintzaiekek / nintzaieken",
      },
      hi: {
        niri: "hintzaidake",
        hari: "hintzaioke",
        guri: "hintzaiguke",
        haiei: "hintzaieke",
      },
      hura: {
        niri: "litzaidake | litzaidakek / litzaidaken",
        hiri: "litzaiake / litzainake",
        hari: "litzaioke | litzaiokek / litzaioken",
        guri: "litzaiguke | litzaigukek / litzaiguken",
        zuri: "litzaizuke",
        zuei: "litzaizueke",
        haiei: "litzaieke | litzaiekek / litzaieken",
      },
      gu: {
        hiri: "gintzaizkiake / gintzaizkinake",
        hari: "gintzaizkioke | gintzaizkiokek / gintzaizkioken",
        zuri: "gintzaizkizuke",
        zuei: "gintzaizkizueke",
        haiei: "gintzaizkieke | gintzaizkiekek / gintzaizkieken",
      },
      zu: {
        niri: "zintzaizkidake",
        hari: "zintzaizkioke",
        guri: "zintzaizkiguke",
        haiei: "zintzaizkieke",
      },
      zuek: {
        niri: "zintzaizkidakete",
        hari: "zintzaizkiokete",
        guri: "zintzaizkigukete",
        haiei: "zintzaizkiekete",
      },
      haiek: {
        niri: "litzaizkidake | litzaizkidakek / litzaizkidaken",
        hiri: "litzaizkiake / litzaizkinake",
        hari: "litzaizkioke | litzaizkiokek / litzaizkioken",
        guri: "litzaizkiguke | litzaizkigukek / litzaizkiguken",
        zuri: "litzaizkizuke",
        zuei: "litzaizkizueke",
        haiei: "litzaizkieke | litzaizkiekek / litzaizkieken",
      },
    },
    nor_nork: {
      nik: {
        hi: "hinduket",
        hura: "nuke | nikek / niken",
        zu: "zintuzket",
        zuek: "zintuzketet",
        haiek: "nituzke | nitizkek / nitizken",
      },
      hik: {
        ni: "nindukek / ninduken",
        hura: "huke",
        gu: "gintuzkek / gintuzken",
        haiek: "hituzke",
      },
      hark: {
        ni: "ninduke | nindikek / nindiken",
        hi: "hinduke",
        hura: "luke | likek / liken",
        gu: "gintuzke | gintzikek / gintizken",
        zu: "zintuzke",
        zuek: "zintuzkete",
        haiek: "lituzke | litizkek / litizken",
      },
      guk: {
        hi: "hindukegu",
        hura: "genuke | genikek / geniken",
        zu: "zintuzkegu",
        zuek: "zintuzketegu",
        haiek: "genituzke | genitizkek / genitizken",
      },
      zuk: {
        ni: "nindukezu",
        hura: "zenuke",
        gu: "gintuzkezu",
        haiek: "zenituzke",
      },
      zuek: {
        ni: "nindukezue",
        hura: "zenukete",
        gu: "gintuzkezue",
        haiek: "zenituzkete",
      },
      haiek: {
        ni: "nindukete | nindiketek / nindiketen",
        hi: "hindukete",
        hura: "lukete | liketek / liketen",
        gu: "gintuzkete | gintizketek / gintizketen",
        zu: "zintuzkete",
        zuek: "zintuzketete",
        haiek: "lituzkete | litizketek / litizketen",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "niake / ninake",
          hari: "nioke | niokek / nioken",
          zuri: "nizuke",
          zuei: "nizueke",
          haiei: "nieke | niekek / nieken",
        },
        hik: {
          niri: "hidake",
          hari: "hioke",
          guri: "higuke",
          haiei: "hieke",
        },
        hark: {
          niri: "lidake | lidakek / lidaken",
          hiri: "liake / linake",
          hari: "lioke | liokek / lioken",
          guri: "liguke | ligukek / liguken",
          zuri: "lizuke",
          zuei: "lizueke",
          haiei: "lieke | liekek / lieken",
        },
        guk: {
          hiri: "geniake / geninake",
          hari: "genioke | geniokek / genioken",
          zuri: "genizuke",
          zuei: "genizueke",
          haiei: "genieke | geniekek / genieken",
        },
        zuk: {
          niri: "zenidake",
          hari: "zenioke",
          guri: "zeniguke",
          haiei: "zenieke",
        },
        zuek: {
          niri: "zenidakete",
          hari: "zeniokete",
          guri: "zenigukete",
          haiei: "zeniekete",
        },
        haiek: {
          niri: "lidakete | lidaketek / lidaketen",
          hiri: "liakete / linakete",
          hari: "liokete | lioketek / lioketen",
          guri: "ligukete | liguketek / liguketen",
          zuri: "lizukete",
          zuei: "lizuekete",
          haiei: "liekete | lieketek / lieketen",
        },
      },
      plurala: {
        nik: {
          hiri: "nizkiake / nizkinake",
          hari: "nizkioke | nizkiokek / nizkioken",
          zuri: "nizkizuke",
          zuei: "nizkizueke",
          haiei: "nizkieke | nizkiekek / nizkieken",
        },
        hik: {
          niri: "hizkidake",
          hari: "hizkioke",
          guri: "hizkiguke",
          haiei: "hizkieke",
        },
        hark: {
          niri: "lizkidake | lizkidakek / lizkidaken",
          hiri: "lizkiake / lizkinake",
          hari: "lizkioke | lizkiokek / lizkioken",
          guri: "lizkiguke | lizkigukek / lizkiguken",
          zuri: "lizkizuke",
          zuei: "lizkizueke",
          haiei: "lizkieke | lizkiekek / lizkieken",
        },
        guk: {
          hiri: "genizkiake / genizkinake",
          hari: "genizkioke | genizkiokek / genizkioken",
          zuri: "genizkizuke",
          zuei: "genizkizueke",
          haiei: "genizkieke | genizkiekek / genizkieken",
        },
        zuk: {
          niri: "zenizkidake",
          hari: "zenizkioke",
          guri: "zenizkigume",
          haiei: "zenizkieke",
        },
        zuek: {
          niri: "zenizkidakete",
          hari: "zenizkiokete",
          guri: "zenizkigukete",
          haiei: "zenizkiekete",
        },
        haiek: {
          niri: "lizkidakete | lizkidaketek / lizkidaketen",
          hiri: "lizkiakete / lizkinakete",
          hari: "lizkiokete | lizkioketek / lizkioketen",
          guri: "lizkigukete | lizkiguketek / lizkiguketen",
          zuri: "lizkizukete",
          zuei: "lizkizuekete",
          haiei: "lizkiekete | lizkieketek / lizkieketen",
        },
      },
    },
  },
  iraganekoa: {
    nor: {
      ni: "nintzatekeen | nindukean / nindukenan",
      hi: "hintzatekeen",
      hura: "zatekeen | zukean / zukenan",
      gu: "ginatekeen | gintuzkean / gintuzkenan",
      zu: "zinatekeen",
      zuek: "zinateketen",
      haiek: "ziratekeen | zituzkean / zituzkenan",
    },
    nor_nori: {
      ni: {
        hiri: "nintzaiakeen / nintzainakeen",
        hari: "nintzaiokeen | nintzaiokean / nintzaiokenan",
        zuri: "nintzaizukeen",
        zuei: "nintzaizuekeen",
        haiei: "nintzaiekeen | nintzaiekean / nintzaiekenan",
      },
      hi: {
        niri: "hintzaidakeen",
        hari: "hintzaiokeen",
        guri: "hintzaigukeen",
        haiei: "hintzaiekeen",
      },
      hura: {
        niri: "zitzaidakeen | zitzaidakean / zitzaidakenan",
        hiri: "zitzaiakeen / zitzainakeen",
        hari: "zitzaiokeen | zitzaiokean / zitzaiokenan",
        guri: "zitzaigukeen | zitzaigukean / zitzaigukenan",
        zuri: "zitzaizukeen",
        zuei: "zitzaizuekeen",
        haiei: "zitzaiekeen | zitzaiekean / zitzaiekenan",
      },
      gu: {
        hiri: "gintzaizkiakeen / gintzaizkinakeen",
        hari: "gintzaizkiokeen | gintzaizkiokean / gintzaizkiokenan",
        zuri: "gintzaizkizukeen",
        zuei: "gintzaizkizuekeen",
        haiei: "gintzaizkiekeen | gintzaizkiekean / gintzaizkiekenan",
      },
      zu: {
        niri: "zintzaizkidakeen",
        hari: "zintzaizkiokeen",
        guri: "zintzaizkigukeen",
        haiei: "zintzaizkiekeen",
      },
      zuek: {
        niri: "zintzaizkidaketen",
        hari: "zintzaizkioketen",
        guri: "zintzaizkiguketen",
        haiei: "zintzaizkieketeen",
      },
      haiek: {
        niri: "zitzaizkidakeen | zitzaizkidakean / zitzaizkidakenan",
        hiri: "zitzaizkiakeen / zitzaizkinakeen",
        hari: "zitzaizkiokeen | zitzaizkiokean / zitzaizkiokenan",
        guri: "zitzaizkigukeen | zitzaizkigukean / zitzaizkigukenan",
        zuri: "zitzaizkizukeen",
        zuei: "zitzaizkizuekeen",
        haiei: "zitzaizkiekeen | zitzaizkiekean / zitzaizkiekenan",
      },
    },
    nor_nork: {
      nik: {
        hi: "hindukedan",
        hura: "nukeen | nikean / nikenan",
        zu: "zintuzkedan",
        zuek: "zintuzketedan",
        haiek: "nituzkeen | nitizkean / nitizkenan",
      },
      hik: {
        ni: "nindukean / nindukenan",
        hura: "hukeen",
        gu: "gintuzkean / gintuzkenan",
        haiek: "hituzkeen",
      },
      hark: {
        ni: "nindukeen | nindikean / nindikenan",
        hi: "hindukeen",
        hura: "zukeen | zikean / zikenan",
        gu: "gintuzkeen | gintzikean / gintizkenan",
        zu: "zintuzkeen",
        zuek: "zintuzketen",
        haiek: "zituzkeen | zitizkean / zitizkenan",
      },
      guk: {
        hi: "hindukegun",
        hura: "genukeen | genikean / genikenan",
        zu: "zintuzkegun",
        zuek: "zintuzketegun",
        haiek: "genituzkeen | genitizkean / genitizkenan",
      },
      zuk: {
        ni: "nindukezun",
        hura: "zenukeen",
        gu: "gintuzkezun",
        haiek: "zenituzkeen",
      },
      zuek: {
        ni: "nindukezuen",
        hura: "zenuketen",
        gu: "gintuzkezuen",
        haiek: "zenituzketen",
      },
      haiek: {
        ni: "ninduketen | nindiketean / nindiketenan",
        hi: "hinduketen",
        hura: "zuketen | ziketean / ziketenan",
        gu: "gintuzketen | gintizketean / gintizketenan",
        zu: "zintuzketen",
        zuek: "zintuzketeten",
        haiek: "zituzketen | zitizketean / zitizketenan",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "niakeen / ninakeen",
          hari: "niokeen | niokean / niokenan",
          zuri: "nizukeen",
          zuei: "nizuekeen",
          haiei: "niekeen | niekean / niekenan",
        },
        hik: {
          niri: "hidakeen",
          hari: "hiokeen",
          guri: "higukeen",
          haiei: "hiekeen",
        },
        hark: {
          niri: "zidakeen | zidakean / zidakenan",
          hiri: "ziakeen / zinakeen",
          hari: "ziokeen | ziokean / ziokenan",
          guri: "zigukeen | zigukean / zigukenan",
          zuri: "zizukeen",
          zuei: "zizuekeen",
          haiei: "ziekeen | ziekean / ziekenan",
        },
        guk: {
          hiri: "geniakeen / geninakeen",
          hari: "geniokeen | geniokean / geniokenan",
          zuri: "genizukeen",
          zuei: "genizuekeen",
          haiei: "geniekeen | geniekean / geniekenan",
        },
        zuk: {
          niri: "zenidakeen",
          hari: "zeniokeen",
          guri: "zenigukeen",
          haiei: "zeniekeen",
        },
        zuek: {
          niri: "zenidaketen",
          hari: "zenioketen",
          guri: "zeniguketen",
          haiei: "zenieketen",
        },
        haiek: {
          niri: "zidaketen | zidaketean / zidaketenan",
          hiri: "ziaketen / zinaketen",
          hari: "zioketeen | zioketean / zioketenan",
          guri: "ziguketen | ziguketean / ziguketenan",
          zuri: "zizuketen",
          zuei: "zizueketen",
          haiei: "zieketen | zieketean / zieketenan",
        },
      },
      plurala: {
        nik: {
          hiri: "nizkiakeen / nizkinakeen",
          hari: "nizkiokeen | nizkiokean / nizkiokenan",
          zuri: "nizkizukeen",
          zuei: "nizkizuekeen",
          haiei: "nizkiekeen | nizkiekean / nizkiekenan",
        },
        hik: {
          niri: "hizkidakeen",
          hari: "hizkiokeen",
          guri: "hizkigukeen",
          haiei: "hizkiekeen",
        },
        hark: {
          niri: "zizkidakeen | zizkidakean / zizkidakenan",
          hiri: "zizkiakeen / zizkinakeen",
          hari: "zizkiokeen | zizkiokean / zizkiokenan",
          guri: "zizkigukeen | zizkigukean / zizkigukenan",
          zuri: "zizkizukeen",
          zuei: "zizkizuekeen",
          haiei: "zizkiekeen | zizkiekean / zizkiekenan",
        },
        guk: {
          hiri: "genizkiakeen / genizkinakeen",
          hari: "genizkiokeen | genizkiokean / genizkiokenan",
          zuri: "genizkizukeen",
          zuei: "genizkizuekeen",
          haiei: "genizkiekeen | genizkiekean /genizkiekenan",
        },
        zuk: {
          niri: "zenizkidakeen",
          hari: "zenizkiokeen",
          guri: "zenizkigukeen",
          haiei: "zenizkiekeen",
        },
        zuek: {
          niri: "zenizkidaketen",
          hari: "zenizkioketen",
          guri: "zenizkiguketen",
          haiei: "zenizkieketen",
        },
        haiek: {
          niri: "zizkidaketen | zizkidaketean / zizkidaketenan",
          hiri: "zizkiaketen / zizkinaketen",
          hari: "zizkioketeen | zizkioketean / zizkioketenan",
          guri: "zizkiguketen | zizkiguketean / zizkiguketenan",
          zuri: "zizkizuketen",
          zuei: "zizkizueketen",
          haiei: "zizkieketen | zizkieketan / zizkieketenan",
        },
      },
    },
  },
};
