import { IIndikatiboaBizkaiera } from "../../common/types/indikatiboaBizkaiera.types";

export const INDIKATIBOA_BIZKAIERA: IIndikatiboaBizkaiera = {
  orain: {
    nor: {
      ni: "naz",
      hi: "haz",
      bera: "da",
      gu: "gara",
      zu: "zara",
      zuek: "zarie",
      eurak: "dira",
    },
    nor_nori: {
      ni: {
        hiri: "natxak / natxan(a) | naiak / naian(a)",
        berari: "natxako | naiako",
        zuri: "natxatzu | naiatzu",
        zuei: "natxatzue | naiatzue",
        eurei: "natxake | naiake",
      },
      hi: {
        niri: "hatxat | haiat",
        berari: "hatxako | haiako",
        guri: "hatxaku | haiaku",
        eurei: "hatxake | haiake",
      },
      bera: {
        niri: "jat",
        hiri: "jak / jan(a)",
        berari: "jako",
        guri: "jaku",
        zuri: "jatzu",
        zuei: "jatzue",
        eurei: "jake",
      },
      gu: {
        hiri: "gatxazak / gatxazan(a) | gaiazak / gaiazan(a)",
        berari: "gatxakoz | gaiakoz",
        zuri: "gatxatzuz | gaiatzuz",
        zuei: "gatxatzuez | gaiatzuez",
        eurei: "gatxakez | gaiakez",
      },
      zu: {
        niri: "zatxataz | zaiataz",
        berari: "zatxakoz | zaiakoz",
        guri: "zatxakuz | zaiakuz",
        eurei: "zatxakez | zaiakez",
      },
      zuek: {
        niri: "zatxataze | zaiataze",
        berari: "zatxakoze | zaiakoze",
        guri: "zatxakuze | zaiakuze",
        eurei: "zatxakeze | zaiakeze",
      },
      eurak: {
        niri: "jataz",
        hiri: "jazak / jazan(a)",
        berari: "jakoz",
        guri: "jakuz",
        zuri: "jatzuz",
        zuei: "jatzuez",
        eurei: "jakez",
      },
    },
    nor_nork: {
      nik: {
        hi: "haut",
        bera: "dot",
        zu: "zaitut",
        zuek: "zaituet",
        eurak: "dodaz | ditut",
      },
      hik: {
        ni: "nok / non(a)",
        bera: "dok / don(a)",
        gu: "gozak / gozan(a) | gaituk / gaitun",
        eurak: "dozak / dozan(a) | dituk / ditun",
      },
      berak: {
        ni: "nau",
        hi: "hau",
        bera: "dau",
        gu: "gaitu",
        zu: "zaitu",
        zuek: "zaitue",
        eurak: "dauz | ditu",
      },
      guk: {
        hi: "haugu",
        bera: "dogu",
        zu: "zaitugu",
        zuek: "zaituegu",
        eurak: "doguz | ditugu",
      },
      zuk: {
        ni: "nozu",
        bera: "dozu",
        gu: "gozuz | gaituzu",
        eurak: "dozuz | dituzu",
      },
      zuek: {
        ni: "nozue",
        bera: "dozue",
        gu: "gozuez | gaituzue",
        eurak: "dozuez | dituzue",
      },
      eurek: {
        ni: "nabe",
        hi: "habe",
        bera: "dabe",
        gu: "gaitue",
        zu: "zaitue",
        zuek: "zaituee",
        eurak: "dabez | ditue",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "deuat / deunat",
          berari: "deutsat",
          zuri: "deutsut",
          zuei: "deutsuet",
          eurei: "deutset",
        },
        hik: {
          niri: "deustak / deustan(a)",
          berari: "deutsak / deutsan(a)",
          guri: "deuskuk / deuskun(a)",
          eurei: "deutsek / deutsen(a)",
        },
        berak: {
          niri: "deust",
          hiri: "deua / deuna",
          berari: "deutso",
          guri: "deusku",
          zuri: "deutsu",
          zuei: "deutsue",
          eurei: "deutse",
        },
        guk: {
          hiri: "deuagu / deunagu",
          berari: "deutsagu",
          zuri: "deutsugu",
          zuei: "deutsuegu",
          eurei: "deutsegu",
        },
        zuk: {
          niri: "deustazu",
          berari: "deutsazu",
          guri: "deuskuzu",
          eurei: "deutsezu",
        },
        zuek: {
          niri: "deustazue",
          berari: "deutsazue",
          guri: "deuskuzue",
          eurei: "deutsezue",
        },
        eurek: {
          niri: "deuste",
          hiri: "deue / deune",
          berari: "deutsie",
          guri: "deuskue",
          zuri: "deutsue",
          zuei: "deutsuee",
          eurei: "deutsee",
        },
      },
      plurala: {
        nik: {
          hiri: "deuadaz / deunadaz",
          berari: "deutsadaz",
          zuri: "deutsudaz",
          zuei: "deutsuedaz",
          eurei: "deutsedaz",
        },
        hik: {
          niri: "deustazak / deustazan(a)",
          berari: "deutsazak / deutsazan(a)",
          guri: "deuskuzak / deuskuzun(a)",
          eurei: "deutsezak / deutsezan(a)",
        },
        berak: {
          niri: "deustaz",
          hiri: "deuaz / deunaz",
          berari: "deutsaz",
          guri: "deuskuz",
          zuri: "deutsuz",
          zuei: "deutsuez",
          eurei: "deutsez",
        },
        guk: {
          hiri: "deuaguz / deunaguz",
          berari: "deutsaguz",
          zuri: "deutsuguz",
          zuei: "deutsueguz",
          eurei: "deutseguz",
        },
        zuk: {
          niri: "deustazuz",
          berari: "deutsazuz",
          guri: "deuskuzuz",
          eurei: "deutsezuz",
        },
        zuek: {
          niri: "deustazuez",
          berari: "deutsazuez",
          guri: "deuskuzuez",
          eurei: "deutsezuez",
        },
        eurek: {
          niri: "deustez",
          hiri: "deuez / deunez",
          berari: "deutsiez",
          guri: "deuskuez",
          zuri: "deutsuez",
          zuei: "deutsueez",
          eurei: "deutseez",
        },
      },
    },
  },
  lehen: {
    nor: {
      ni: "nintzan",
      hi: "hintzan",
      bera: "zan",
      gu: "ginan",
      zu: "zinan",
      zuek: "zinien",
      eurak: "ziran",
    },
    nor_nori: {
      ni: {
        hiri: "nintxaan / nintxanan",
        berari: "nintxakon",
        zuri: "nintxatzun",
        zuei: "nintxatzuen",
        eurei: "nintxaken",
      },
      hi: {
        niri: "hintxatan",
        berari: "hintxakon",
        guri: "hintxakun",
        eurei: "hintxaken",
      },
      bera: {
        niri: "jatan",
        hiri: "jaan / janan",
        berari: "jakon",
        guri: "jakun",
        zuri: "jatzun",
        zuei: "jatzuen",
        eurei: "jaken",
      },
      gu: {
        hiri: "gintxaazan / gintxazanan",
        berari: "gintxakozan",
        zuri: "gintxatzuzan",
        zuei: "gintxatzuezan",
        eurei: "gintxakezan",
      },
      zu: {
        niri: "zintxatazan",
        berari: "zintxakozan",
        guri: "zintxakuzan",
        eurei: "zintxakezan",
      },
      zuek: {
        niri: "zintxatazen",
        berari: "zintxakozen",
        guri: "zintxakuzen",
        eurei: "zitxakezen",
      },
      eurak: {
        niri: "jatazan",
        hiri: "jaazan / jazanan",
        berari: "jakozan",
        guri: "jakuzan",
        zuri: "jatzuzan",
        zuei: "jatzuezan",
        eurei: "jakezan",
      },
    },
    nor_nork: {
      nik: {
        hi: "hindudan",
        bera: "neban",
        zu: "zindudazan",
        zuek: "zinduedazan",
        eurak: "nebazan | nituan",
      },
      hik: {
        ni: "ninduan / nindunan",
        bera: "heuan",
        gu: "ginduazan / ginduzanan",
        eurak: "heuazan / hituan",
      },
      berak: {
        ni: "ninduan",
        hi: "hinduan",
        bera: "(z)eban",
        gu: "ginduzan",
        zu: "zinduzan",
        zuek: "zinduezan",
        eurak: "ebazan | zituan",
      },
      guk: {
        hi: "hindugun",
        bera: "genduan",
        zu: "zinduguzan",
        zuek: "zindueguzan",
        eurak: "genduzan",
      },
      zuk: {
        ni: "ninduzun",
        bera: "zenduan",
        gu: "ginduzuzan",
        eurak: "zenduzan",
      },
      zuek: {
        ni: "ninduzuen",
        bera: "zenduen",
        gu: "ginduzuezan",
        eurak: "zenduezan",
      },
      eurek: {
        ni: "ninduen",
        hi: "hinduen",
        bera: "(z)eben",
        gu: "ginduezan",
        zu: "zinduezan",
        zuek: "zindueezan",
        eurak: "ebezan | zituen",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "neuan / neunan",
          berari: "neutsan",
          zuri: "neutsun",
          zuei: "neutsuen",
          eurei: "neutsen",
        },
        hik: {
          niri: "heustan",
          berari: "heutsan",
          guri: "heuskun",
          eurei: "heutsen",
        },
        berak: {
          niri: "eustan",
          hiri: "euan / eunan",
          berari: "eutsan",
          guri: "euskun",
          zuri: "eutsun",
          zuei: "eutsuen",
          eurei: "eutsen",
        },
        guk: {
          hiri: "geuan / geunan",
          berari: "geuntsan",
          zuri: "geuntsun",
          zuei: "geuntsuen",
          eurei: "geuntsen",
        },
        zuk: {
          niri: "zeunstan",
          berari: "zeuntsan",
          guri: "zeunskun",
          eurei: "zeuntsen",
        },
        zuek: {
          niri: "zeunsten",
          berari: "zeuntsien",
          guri: "zeunskuen",
          eurei: "zeuntseen",
        },
        eurek: {
          niri: "eusten",
          hiri: "euen / eunen",
          berari: "eutsien",
          guri: "euskuen",
          zuri: "eutsuen",
          zuei: "eutsueen",
          eurei: "eutseen",
        },
      },
      plurala: {
        nik: {
          hiri: "neuazan / neunazan",
          berari: "neutsazan",
          zuri: "neutsuzan",
          zuei: "neutsuezan",
          eurei: "neutsezan",
        },
        hik: {
          niri: "heustazan",
          berari: "heutsazan",
          guri: "heuskuzan",
          eurei: "heutsezan",
        },
        berak: {
          niri: "eustazan",
          hiri: "euazan / eunazan",
          berari: "eutsazan",
          guri: "euskuzan",
          zuri: "eutsuzan",
          zuei: "eutsuezan",
          eurei: "eutsezan",
        },
        guk: {
          hiri: "geuazan / geunazan",
          berari: "geuntsazan",
          zuri: "geuntsuzan",
          zuei: "geuntsuezan",
          eurei: "geuntsezan",
        },
        zuk: {
          niri: "zeunstazan",
          berari: "zeuntsazan",
          guri: "zeunskuzan",
          eurei: "zeuntsezan",
        },
        zuek: {
          niri: "zeunstezan",
          berari: "zeuntsiezan",
          guri: "zeunskuezan",
          eurei: "zeuntseezan",
        },
        eurek: {
          niri: "eustezan",
          hiri: "euezan / eunezan",
          berari: "eutsiezan",
          guri: "euskuezan",
          zuri: "eutsuezan",
          zuei: "eutsueezan",
          eurei: "eutseezan",
        },
      },
    },
  },
  baldintza: {
    nor: {
      ni: "banintz",
      hi: "bahintz",
      bera: "balitz",
      gu: "bagina",
      zu: "bazina",
      zuek: "bazinie",
      eurak: "balira",
    },
    nor_nori: {
      ni: {
        hiri: "banintxaa / banintxan(a)",
        berari: "banintxako",
        zuri: "banintxazu",
        zuei: "banintxatzue",
        eurei: "banintxake",
      },
      hi: {
        niri: "bahintxat",
        berari: "bahintxako",
        guri: "bahintxaku",
        eurei: "bahintxake",
      },
      bera: {
        niri: "balitxat",
        hiri: "balitxaa / balitxan(a)",
        berari: "balitxako",
        guri: "balitxaku",
        zuri: "balitxazu",
        zuei: "balitxatzue",
        eurei: "balitxake",
      },
      gu: {
        hiri: "bagintxaaz / bagintxanaz",
        berari: "bagintxakoz",
        zuri: "bagintxatzuz",
        zuei: "bagintxatzuez",
        eurei: "bagintxakez",
      },
      zu: {
        niri: "bazintxataz",
        berari: "bazintxakoz",
        guri: "bazintxakuz",
        eurei: "bazintxakez",
      },
      zuek: {
        niri: "bazintxataze",
        berari: "bazintxakoze",
        guri: "bazintxakuze",
        eurei: "bazintxakeze",
      },
      eurak: {
        niri: "balitxataz",
        hiri: "balitxaaz / balitxanaz",
        berari: "balitxakoz",
        guri: "balitxakuz",
        zuri: "balitxatzuz",
        zuei: "balitxatzuez",
        eurei: "balitxakez",
      },
    },
    nor_nork: {
      nik: {
        hi: "bahindut",
        bera: "baneu",
        zu: "bazindudaz",
        zuek: "bazinduedaz",
        eurak: "baneuz | banitu",
      },
      hik: {
        ni: "baninduk / banindun(a)",
        bera: "baheu",
        gu: "baginduzak / baginduzan(a)",
        eurak: "baheuz | bahitu",
      },
      berak: {
        ni: "banindu",
        hi: "bahindu",
        bera: "baleu",
        gu: "baginduz",
        zu: "bazinduz",
        zuek: "bazinduez",
        eurak: "baleuz / balitu",
      },
      guk: {
        hi: "bahindugu",
        bera: "bagendu",
        zu: "bazinduguz",
        zuek: "bazindueguz",
        eurak: "bagenduz",
      },
      zuk: {
        ni: "baninduzu",
        bera: "bazendu",
        gu: "baginduzuz",
        eurak: "bazenduz",
      },
      zuek: {
        ni: "baninduzue",
        bera: "bazendue",
        gu: "baginduzuez",
        eurak: "bazenduez",
      },
      eurek: {
        ni: "banindue",
        hi: "bahindue",
        bera: "balebe",
        gu: "baginduez",
        zu: "bazinduez",
        zuek: "bazindueez",
        eurak: "balebez / balitue",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "baneua / baneuna",
          berari: "baneutso",
          zuri: "baneutsu",
          zuei: "baneutsue",
          eurei: "baneutse",
        },
        hik: {
          niri: "baheust",
          berari: "baheutso",
          guri: "baheusku",
          eurei: "beheutse",
        },
        berak: {
          niri: "baleust",
          hiri: "baleua / baleuna",
          berari: "baleutso",
          guri: "baleusku",
          zuri: "baleutsu",
          zuei: "baleutsue",
          eurei: "baleutse",
        },
        guk: {
          hiri: "bageundua / bagenduna",
          berari: "bageuntso",
          zuri: "bageuntsu",
          zuei: "bageuntsue",
          eurei: "bageuntse",
        },
        zuk: {
          niri: "bazeunst",
          berari: "bazeuntso",
          guri: "bazeunsku",
          eurei: "bazeuntse",
        },
        zuek: {
          niri: "bazeunste",
          berari: "bazeuntsie",
          guri: "bazeunskue",
          eurei: "bazeuntsee",
        },
        eurek: {
          niri: "baleuste",
          hiri: "baleue / baleune",
          berari: "baleutsie",
          guri: "baleuskue",
          zuri: "baleutsue",
          zuei: "baleutsuee",
          eurei: "baleutsee",
        },
      },
      plurala: {
        nik: {
          hiri: "baneuaz / baneunaz",
          berari: "baneutsaz",
          zuri: "baneutsuz",
          zuei: "baneutsuez",
          eurei: "baneutsez",
        },
        hik: {
          niri: "baheustaz",
          berari: "baheutsaz",
          guri: "baheuskuz",
          eurei: "baheutsez",
        },
        berak: {
          niri: "baleustaz",
          hiri: "baleuaz / baleunaz",
          berari: "baleutsaz",
          guri: "baleuskuz",
          zuri: "baleutsuz",
          zuei: "baleutsuez",
          eurei: "baleutsez",
        },
        guk: {
          hiri: "bagenduaz / bagendunaz",
          berari: "bageuntsaz",
          zuri: "bageuntsuz",
          zuei: "bageuntsuez",
          eurei: "bageuntsez",
        },
        zuk: {
          niri: "bazeunstaz",
          berari: "bazeuntsaz",
          guri: "bazeunskuz",
          eurei: "bazeuntsez",
        },
        zuek: {
          niri: "bazeunstez",
          berari: "bazeuntsiez",
          guri: "bazeunskuez",
          eurei: "bazeuntseez",
        },
        eurek: {
          niri: "baleustez",
          hiri: "baleuez / baleunez",
          berari: "baleutsiez",
          guri: "baleuskuez",
          zuri: "baleutsuez",
          zuei: "baleutsueez",
          eurei: "baleutseez",
        },
      },
    },
  },
  etorkizunekoa: {
    nor: {
      ni: "nintzateke",
      hi: "hintzateke",
      bera: "litzateke",
      gu: "gintzatekez",
      zu: "zintzatekez",
      zuek: "zintzatekeze",
      eurak: "litzatekez",
    },
    nor_nori: {
      ni: {
        hiri: "",
        berari: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      hi: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      bera: {
        niri: "",
        hiri: "",
        berari: "",
        guri: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      gu: {
        hiri: "",
        berari: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      zu: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      zuek: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      eurak: {
        niri: "",
        hiri: "",
        berari: "",
        guri: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        bera: "neuke",
        zu: "",
        zuek: "",
        eurak: "neukez",
      },
      hik: {
        ni: "",
        bera: "heunke",
        gu: "",
        eurak: "heunkez",
      },
      berak: {
        ni: "",
        hi: "",
        bera: "leuke",
        gu: "",
        zu: "",
        zuek: "",
        eurak: "leukez",
      },
      guk: {
        hi: "",
        bera: "geunke",
        zu: "",
        zuek: "",
        eurak: "geunkez",
      },
      zuk: {
        ni: "",
        bera: "zeunke",
        gu: "",
        eurak: "zeunkez",
      },
      zuek: {
        ni: "",
        bera: "zeunkie",
        gu: "",
        eurak: "zeunkiez",
      },
      eurek: {
        ni: "",
        hi: "",
        bera: "leukie",
        gu: "",
        zu: "",
        zuek: "",
        eurak: "leukiez",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        hik: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        berak: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        guk: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        zuk: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        zuek: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        eurek: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        hik: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        berak: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        guk: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        zuk: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        zuek: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        eurek: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
      },
    },
  },
  iraganekoa: {
    nor: {
      ni: "nintzatekean",
      hi: "hintzatekean",
      bera: "litzatekean",
      gu: "gintzatekezan",
      zu: "zintzatekezan",
      zuek: "zintzatekezen",
      eurak: "litzatekezan",
    },
    nor_nori: {
      ni: {
        hiri: "",
        berari: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      hi: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      bera: {
        niri: "",
        hiri: "",
        berari: "",
        guri: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      gu: {
        hiri: "",
        berari: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
      zu: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      zuek: {
        niri: "",
        berari: "",
        guri: "",
        eurei: "",
      },
      eurak: {
        niri: "",
        hiri: "",
        berari: "",
        guri: "",
        zuri: "",
        zuei: "",
        eurei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        bera: "neukean",
        zu: "",
        zuek: "",
        eurak: "neukeza",
      },
      hik: {
        ni: "",
        bera: "heunkean",
        gu: "",
        eurak: "heunkezan",
      },
      berak: {
        ni: "",
        hi: "",
        bera: "leukean",
        gu: "",
        zu: "",
        zuek: "",
        eurak: "leukezan",
      },
      guk: {
        hi: "",
        bera: "geunkean",
        zu: "",
        zuek: "",
        eurak: "geunkezan",
      },
      zuk: {
        ni: "",
        bera: "zeunkean",
        gu: "",
        eurak: "zeunkezan",
      },
      zuek: {
        ni: "",
        bera: "zeunkien",
        gu: "",
        eurak: "zeunkiezan",
      },
      eurek: {
        ni: "",
        hi: "",
        bera: "leukien",
        gu: "",
        zu: "",
        zuek: "",
        eurak: "leukiezan",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        hik: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        berak: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        guk: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        zuk: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        zuek: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        eurek: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        hik: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        berak: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        guk: {
          hiri: "",
          berari: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
        zuk: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        zuek: {
          niri: "",
          berari: "",
          guri: "",
          eurei: "",
        },
        eurek: {
          niri: "",
          hiri: "",
          berari: "",
          guri: "",
          zuri: "",
          zuei: "",
          eurei: "",
        },
      },
    },
  },
};
