import { IIndikatiboaZuberera } from "../../common/types/indikatiboaZuberera.types";

export const INDIKATIBOA_ZUBERERA: IIndikatiboaZuberera = {
  orain: {
    nor: {
      ni: "niz",
      hi: "hiz",
      hura: "da",
      gu: "gira",
      zu: "zira",
      zuek: "zirade(i)e",
      haiek: "dira",
    },
    nor_nori: {
      ni: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      hi: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      hura: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      gu: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      zu: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      zuek: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      haiek: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      hik: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      hark: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      guk: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      zuk: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      zuek: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      haiek: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
    },
  },
  lehen: {
    nor: {
      ni: "nintzan",
      hi: "hintzan",
      hura: "zen",
      gu: "ginen",
      zu: "zinen",
      zuek: "zinde(i)en",
      haiek: "ziren",
    },
    nor_nori: {
      ni: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      hi: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      hura: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      gu: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      zu: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      zuek: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      haiek: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        hura: "nian",
        zu: "",
        zuek: "",
        haiek: "nütian",
      },
      hik: {
        ni: "",
        hura: "hian",
        gu: "",
        haiek: "hütian",
      },
      hark: {
        ni: "",
        hi: "",
        hura: "zian",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "zütian",
      },
      guk: {
        hi: "",
        hura: "günian",
        zu: "",
        zuek: "",
        haiek: "güntian",
      },
      zuk: {
        ni: "",
        hura: "zünian",
        gu: "",
        haiek: "züntian",
      },
      zuek: {
        ni: "",
        hura: "zünien",
        gu: "",
        haiek: "züntien",
      },
      haiek: {
        ni: "",
        hi: "",
        hura: "zien",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "zütien",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
    },
  },
  baldintza: {
    nor: {
      ni: "",
      hi: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    nor_nori: {
      ni: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      hi: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      hura: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      gu: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      zu: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      zuek: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      haiek: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      hik: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      hark: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      guk: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      zuk: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      zuek: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      haiek: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
    },
  },
  etorkizunekoa: {
    nor: {
      ni: "",
      hi: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    nor_nori: {
      ni: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      hi: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      hura: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      gu: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      zu: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      zuek: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      haiek: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      hik: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      hark: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      guk: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      zuk: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      zuek: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      haiek: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
    },
  },
  iraganekoa: {
    nor: {
      ni: "",
      hi: "",
      hura: "",
      gu: "",
      zu: "",
      zuek: "",
      haiek: "",
    },
    nor_nori: {
      ni: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      hi: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      hura: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      gu: {
        hiri: "",
        hari: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
      zu: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      zuek: {
        niri: "",
        hari: "",
        guri: "",
        haiei: "",
      },
      haiek: {
        niri: "",
        hiri: "",
        hari: "",
        guri: "",
        zuri: "",
        zuei: "",
        haiei: "",
      },
    },
    nor_nork: {
      nik: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      hik: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      hark: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      guk: {
        hi: "",
        hura: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
      zuk: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      zuek: {
        ni: "",
        hura: "",
        gu: "",
        haiek: "",
      },
      haiek: {
        ni: "",
        hi: "",
        hura: "",
        gu: "",
        zu: "",
        zuek: "",
        haiek: "",
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
      plurala: {
        nik: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        hik: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        hark: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        guk: {
          hiri: "",
          hari: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
        zuk: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        zuek: {
          niri: "",
          hari: "",
          guri: "",
          haiei: "",
        },
        haiek: {
          niri: "",
          hiri: "",
          hari: "",
          guri: "",
          zuri: "",
          zuei: "",
          haiei: "",
        },
      },
    },
  },
};
