export const INDIKATIBOA_ADITZ_EREDUA = {
  orain: {
    nor: {
      ni: '',
      hi: '',
      hura: '',
      gu: '',
      zu: '',
      zuek: '',
      haiek: '',
    },
    nor_nori: {
      ni: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      hi: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      hura: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      gu: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      zu: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      zuek: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      haiek: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
    },
    nor_nork: {
      nik: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      hik: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      hark: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      guk: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      zuk: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      zuek: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      haiek: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
      plurala: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
    },
  },
  lehen: {
    nor: {
      ni: '',
      hi: '',
      hura: '',
      gu: '',
      zu: '',
      zuek: '',
      haiek: '',
    },
    nor_nori: {
      ni: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      hi: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      hura: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      gu: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      zu: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      zuek: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      haiek: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
    },
    nor_nork: {
      nik: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      hik: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      hark: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      guk: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      zuk: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      zuek: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      haiek: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
      plurala: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
    },
  },
  baldintza: {
    nor: {
      ni: '',
      hi: '',
      hura: '',
      gu: '',
      zu: '',
      zuek: '',
      haiek: '',
    },
    nor_nori: {
      ni: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      hi: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      hura: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      gu: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      zu: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      zuek: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      haiek: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
    },
    nor_nork: {
      nik: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      hik: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      hark: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      guk: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      zuk: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      zuek: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      haiek: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
      plurala: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
    },
  },
  etorkizunekoa: {
    nor: {
      ni: '',
      hi: '',
      hura: '',
      gu: '',
      zu: '',
      zuek: '',
      haiek: '',
    },
    nor_nori: {
      ni: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      hi: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      hura: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      gu: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      zu: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      zuek: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      haiek: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
    },
    nor_nork: {
      nik: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      hik: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      hark: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      guk: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      zuk: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      zuek: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      haiek: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
      plurala: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
    },
  },
  iraganekoa: {
    nor: {
      ni: '',
      hi: '',
      hura: '',
      gu: '',
      zu: '',
      zuek: '',
      haiek: '',
    },
    nor_nori: {
      ni: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      hi: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      hura: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      gu: {
        hiri: '',
        hari: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
      zu: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      zuek: {
        niri: '',
        hari: '',
        guri: '',
        haiei: '',
      },
      haiek: {
        niri: '',
        hiri: '',
        hari: '',
        guri: '',
        zuri: '',
        zuei: '',
        haiei: '',
      },
    },
    nor_nork: {
      nik: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      hik: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      hark: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      guk: {
        hi: '',
        hura: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
      zuk: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      zuek: {
        ni: '',
        hura: '',
        gu: '',
        haiek: '',
      },
      haiek: {
        ni: '',
        hi: '',
        hura: '',
        gu: '',
        zu: '',
        zuek: '',
        haiek: '',
      },
    },
    nor_nori_nork: {
      singularra: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
      plurala: {
        nik: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        hik: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        hark: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        guk: {
          hiri: '',
          hari: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
        zuk: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        zuek: {
          niri: '',
          hari: '',
          guri: '',
          haiei: '',
        },
        haiek: {
          niri: '',
          hiri: '',
          hari: '',
          guri: '',
          zuri: '',
          zuei: '',
          haiei: '',
        },
      },
    },
  },
};
